project:
  type: website
  output-dir: docs

website:
  title: "Safia Mariyam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Contact 
      - href: CV.qmd
        text: CV
      - href: blog.qmd
        text: BLOG

format:
  html:
    theme:
      - dracula
      - brand
    css: styles.css
    toc: true

editor: visual

