project:
  type: website
  output-dir: docs
  
resources: 
- files/econ_2204_assignment_1.pdf

website:
  title: "Safia Mariyam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Contact 
      - href: CV.qmd
        text: CV
      - href: blog.qmd
        text: Assignment Blogs

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

